name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    # Limit the permissions of the github token so that the script don't
    # accidently do more than it should
    permissions:
      contents: read
      packages: write
      actions: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts
      - run: npm ci

      # Consumes GitHub API to check if last test run passed
      - id: get_test_workflow_id
        run: |
          curl https://api.github.com/repos/leonardoraele/json-rpc-dual-engine/actions/workflows/test.yml \
          | npx json id
      - https://api.github.com/repos/leonardoraele/json-rpc-dual-engine/actions/workflows/8618439/runs

      # Publish to NPM
      - run: npm publish
        env:
          NPM_CONFIG_REGISTRY: https://registry.npmjs.org/
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      # Publish to GitHub
      - run: npm publish
        env:
          NPM_CONFIG_REGISTRY: https://npm.pkg.github.com/
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
