name: Publish

on:
  workflow_dispatch: ~
  push:
    branches:
      - master
    tags:
      - v[0-9]*
  release:
    types:
      - created

jobs:
  publish_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: '22'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish_github:
    runs-on: ubuntu-latest
    # Limit the permissions of the github token so that the script don't
    # accidently do more than it should
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version: '22'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
